# Basic configuration
# You can create multiple regions as you need, in a list.
# Any subsection of 'areas' is treated as a region.  The key name
# does not matter too much, but is used in logging.
# World names match the world name used for the save folder.
# IE, 'world', 'world_nether', 'world_the_end'.

areas:
  arena1:
    world: world
    x1: 56
    y1: 56
    z1: 56
    x2: 72
    y2: 72
    z2: 72
  arena2:
    world: world_nether
    x1: 1024
    y1: 56
    z1: 1024
    x2: 2048
    y2: 64
    z2: 1040